# Generated by Django 3.1.5 on 2021-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_unit', models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('YEN', '¥')], default='INR', max_length=20)),
                ('course_mode', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3'), ('test4', 'test4')], default='test1', max_length=20)),
                ('pre_requistes', models.CharField(max_length=500)),
                ('published_date', models.DateTimeField(blank=True, default=None)),
            ],
        ),
    ]
