# Generated by Django 3.1.5 on 2021-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courses',
            name='pre_requistes',
            field=models.TextField(max_length=500),
        ),
    ]
