# Generated by Django 3.1.5 on 2021-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210116_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_url',
            field=models.URLField(default='localhost:8000'),
            preserve_default=False,
        ),
    ]
