# Generated by Django 3.1.5 on 2021-01-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210116_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='pre_requistes',
            new_name='prerequistes',
        ),
    ]
