# Generated by Django 3.1.5 on 2021-01-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210117_0116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_table',
        ),
    ]
