# Generated by Django 3.1.5 on 2021-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(choices=[('Default', 'Default'), ('Facebook', 'fb'), ('Google', 'G')], default='Default', max_length=20),
        ),
    ]
