# Generated by Django 3.1.5 on 2021-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(choices=[('Default', 'Default'), ('fb', 'Facebook'), ('G', 'Google')], default='Default', max_length=20),
        ),
    ]
