# Generated by Django 3.1.5 on 2021-01-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=100)),
                ('price_unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=20)),
                ('course_mode', models.CharField(max_length=100)),
                ('course_url', models.URLField()),
                ('published_date', models.DateTimeField(blank=True, default=None)),
                ('duration', models.DateTimeField(blank=True, default=None)),
                ('prerequistes', models.TextField(default=None, max_length=500)),
                ('description', models.TextField(default=None, max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add Course',
                'verbose_name_plural': 'Add Course',
            },
        ),
    ]
